INSERT INTO categories (name)
VALUES ('Fresh Produce'),
       ('Dairy'),
       ('Meat & Seafood'),
       ('Bakery'),
       ('Beverages'),
       ('Snacks'),
       ('Frozen Foods'),
       ('Pantry'),
       ('Household'),
       ('Personal Care');

INSERT INTO products (name, price, description, category_id)
VALUES ('Organic Bananas (1kg)',
        3.49,
        'Fresh organic bananas sourced from local farms. Rich in potassium and perfect for snacks or smoothies.',
        1),
       ('Full Cream Milk 2L',
        4.29,
        'Fresh full cream cow’s milk with a rich taste. Ideal for coffee, cereal, and cooking.',
        2),
       ('Chicken Breast Fillets (500g)',
        9.99,
        'Lean and tender chicken breast fillets, perfect for grilling, baking, or stir-frying.',
        3),
       ('Sourdough Bread Loaf',
        5.49,
        'Artisan sourdough bread baked daily with a crispy crust and soft interior.',
        4),
       ('Orange Juice No Added Sugar 1L',
        4.99,
        '100% pure squeezed orange juice with no added sugar or preservatives.',
        5),
       ('Salted Potato Chips 150g',
        3.79,
        'Classic crispy potato chips lightly seasoned with sea salt.',
        6),
       ('Frozen Margherita Pizza',
        6.99,
        'Stone-baked frozen pizza topped with tomato sauce, mozzarella cheese, and basil.',
        7),
       ('Basmati Rice 5kg',
        18.99,
        'Premium long-grain basmati rice with a fragrant aroma and fluffy texture.',
        8),
       ('Dishwashing Liquid Lemon 750ml',
        3.99,
        'Powerful grease-cutting dishwashing liquid with a fresh lemon scent.',
        9),
       ('Shampoo Daily Moisture 400ml',
        7.49,
        'Gentle daily-use shampoo formulated to hydrate and strengthen hair.',
        10);
